"""empty message

Revision ID: ca8ad8ba5ed4
Revises: 89ef3c533e84
Create Date: 2026-08-02 14:18:22.048608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8ad8ba5ed4'
down_revision = '89ef3c533e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workoutexercises', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.drop_column('workoutexercises', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workoutexercises', sa.Column('duration', sa.INTEGER(), nullable=True))
    op.drop_column('workoutexercises', 'duration_seconds')
    # ### end Alembic commands ###
